# Generated by Django 5.0.1 on 2024-03-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_author_is_verified_alter_author_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
