# Generated by Django 5.0.1 on 2024-03-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_author_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.TextField(),
        ),
    ]
