# Generated by Django 5.0.1 on 2024-01-15 15:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('question', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.date.today, verbose_name='Date published')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update')),
                ('status', models.CharField(default='published', max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.question')),
            ],
            options={
                'db_table': 'Choices',
            },
        ),
    ]
