# Generated by Django 5.0.3 on 2024-04-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_hide_poll', 'can hide poll')]},
        ),
    ]
