# Generated by Django 5.0.1 on 2024-03-05 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_alter_choice_question_alter_question_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_user_question_title',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_question_title', violation_error_message='Title already exists'),
        ),
    ]
